grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	greetings+=Greeting*;
	
Greeting:
	'Hello' name=ID '!';

// redefinition of ID to demonstrate setting of the encoding when reading files containing german umlauts 
terminal ID : ('a'..'z'|'A'..'Z'|'Ä'|'Ö'|'Ü'|'ä'|'ö'|'ü'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9'|'Ä'|'Ö'|'Ü'|'ä'|'ö'|'ü')*;
	